[package]
name = "vpk_cfgy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
once_cell = "1.19.0"
regex = "1.10.3"
tempfile = "3.10.0"
walkdir = "2.4.0"
