[package]
name = "vpk_cfgy"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "0.13.0"
json = "0.12.4"
once_cell = "1.19.0"
tempfile = "3.10.0"
walkdir = "2.4.0"
